# Generated by Django 5.2.8 on 2025-11-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatAcids',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nlc_g_field', models.FloatField(blank=True, db_column='NLC (g)', null=True)),
                ('pufa_g_field', models.FloatField(blank=True, db_column='PUFA (g)', null=True)),
                ('cholesterin_g_field', models.FloatField(blank=True, db_column='Cholesterin (g)', null=True)),
            ],
            options={
                'db_table': 'Fat_Acids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodProducts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
            ],
            options={
                'db_table': 'Food_Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodProductTypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
            ],
            options={
                'db_table': 'Food_Product_Types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Macronutrients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('protein_g_field', models.FloatField(blank=True, db_column='Protein (g)', null=True)),
                ('fats_g_field', models.FloatField(blank=True, db_column='Fats (g)', null=True)),
                ('carbs_g_field', models.FloatField(blank=True, db_column='Carbs (g)', null=True)),
                ('mds_g_field', models.FloatField(blank=True, db_column='MDS (g)', null=True)),
                ('starch_g_field', models.FloatField(blank=True, db_column='Starch (g)', null=True)),
                ('water_g_field', models.FloatField(blank=True, db_column='Water (g)', null=True)),
                ('energy_value_kcal_field', models.FloatField(blank=True, db_column='Energy_Value (kcal)', null=True)),
                ('dietary_fiber_g_field', models.FloatField(blank=True, db_column='Dietary_Fiber (g)', null=True)),
            ],
            options={
                'db_table': 'Macronutrients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minerals',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('na_mg_field', models.FloatField(blank=True, db_column='Na (mg)', null=True)),
                ('k_mg_field', models.FloatField(blank=True, db_column='K (mg)', null=True)),
                ('mg_mg_field', models.FloatField(blank=True, db_column='Mg (mg)', null=True)),
                ('p_mg_field', models.FloatField(blank=True, db_column='P (mg)', null=True)),
                ('fe_mg_field', models.FloatField(blank=True, db_column='Fe (mg)', null=True)),
                ('ash_g_field', models.FloatField(blank=True, db_column='Ash (g)', null=True)),
                ('ca_mg_field', models.FloatField(blank=True, db_column='Ca (mg)', null=True)),
            ],
            options={
                'db_table': 'Minerals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherNutrients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('organic_acids_g_field', models.FloatField(blank=True, db_column='Organic_Acids (g)', null=True)),
                ('alcohol_field', models.FloatField(blank=True, db_column='Alcohol (%)', null=True)),
            ],
            options={
                'db_table': 'Other_Nutrients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('a_vitamin_mg_field', models.FloatField(blank=True, db_column='A_Vitamin (mg)', null=True)),
                ('beta_carotene_mg_field', models.FloatField(blank=True, db_column='Beta_Carotene (mg)', null=True)),
                ('b1_vitamin_mg_field', models.FloatField(blank=True, db_column='B1_Vitamin (mg)', null=True)),
                ('b2_vitamin_mg_field', models.FloatField(blank=True, db_column='B2_Vitamin (mg)', null=True)),
                ('pp_vitamin_mg_field', models.FloatField(blank=True, db_column='PP_Vitamin (mg)', null=True)),
                ('c_vitamin_mg_field', models.FloatField(blank=True, db_column='C_Vitamin (mg)', null=True)),
                ('retinol_index', models.FloatField(blank=True, db_column='Retinol_Index', null=True)),
                ('tocopherol_index', models.FloatField(blank=True, db_column='Tocopherol_Index', null=True)),
                ('niacin_index', models.FloatField(blank=True, db_column='Niacin_Index', null=True)),
            ],
            options={
                'db_table': 'Vitamins',
                'managed': False,
            },
        ),
    ]
